- name: Install GNU C++ Compiler
  community.general.rpm_ostree_pkg:
    name: "{{ item }}"
    state: present
  loop:
    - gcc # C compiler
    - gpp # C++ compiler
    - g++ # linker
  become: true
  notify:
  - Reboot
